esphome:
  name: "${snake_node_name}"

bk72xx:
  board: cb2s

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret node_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

switch:
  - platform: gpio
    name: "${node_name}"
    id: internal_switch
    pin: P24
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

binary_sensor:
  - platform: gpio
    id: external_switch
    pin:
      number: P7
      mode: INPUT_PULLUP
    filters:
     - delayed_on_off: 100ms
    on_state:
      then:
       - switch.toggle: internal_switch

output:
  - platform: gpio
    id: led
    pin: P8

